
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.morevarients.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.morevarients.block.YellowTerracottaStairsBlock;
import net.mcreator.morevarients.block.YellowTerracottaSlabBlock;
import net.mcreator.morevarients.block.YellowConcreteStairsBlock;
import net.mcreator.morevarients.block.YellowConcreteSlabBlock;
import net.mcreator.morevarients.block.WhiteTerracottaSlabBlock;
import net.mcreator.morevarients.block.WhiteTerracottaBlock;
import net.mcreator.morevarients.block.WhiteConcreteStairsBlock;
import net.mcreator.morevarients.block.WhiteConcreteSlabBlock;
import net.mcreator.morevarients.block.WarpedStairsBlock;
import net.mcreator.morevarients.block.WarpedMosaicSlabBlock;
import net.mcreator.morevarients.block.WarpedMosaicBlock;
import net.mcreator.morevarients.block.ThatchedSlabBlock;
import net.mcreator.morevarients.block.ThacthedStairsBlock;
import net.mcreator.morevarients.block.TerracottaStairsBlock;
import net.mcreator.morevarients.block.TerracottaSlabBlock;
import net.mcreator.morevarients.block.SpruceMosaicStairsBlock;
import net.mcreator.morevarients.block.SpruceMosaicSlabBlock;
import net.mcreator.morevarients.block.SpruceMosaicBlock;
import net.mcreator.morevarients.block.SmoothWarpedStairsBlock;
import net.mcreator.morevarients.block.SmoothWarpedSlabBlock;
import net.mcreator.morevarients.block.SmoothWarpedPlanksBlock;
import net.mcreator.morevarients.block.SmoothStoneStairsBlock;
import net.mcreator.morevarients.block.SmoothSpruceSlabBlock;
import net.mcreator.morevarients.block.SmoothSpruceSairsBlock;
import net.mcreator.morevarients.block.SmoothSprucePlanksBlock;
import net.mcreator.morevarients.block.SmoothQuartzWallsBlock;
import net.mcreator.morevarients.block.SmoothOakStairsBlock;
import net.mcreator.morevarients.block.SmoothOakSlabBlock;
import net.mcreator.morevarients.block.SmoothOakPlanksBlock;
import net.mcreator.morevarients.block.SmoothMangroveStairsBlock;
import net.mcreator.morevarients.block.SmoothMangroveSlabBlock;
import net.mcreator.morevarients.block.SmoothMangrovePlanksBlock;
import net.mcreator.morevarients.block.SmoothJungleStairsBlock;
import net.mcreator.morevarients.block.SmoothJungleSlabBlock;
import net.mcreator.morevarients.block.SmoothJunglePlanksBlock;
import net.mcreator.morevarients.block.SmoothDarkOakStairsBlock;
import net.mcreator.morevarients.block.SmoothDarkOakSlabBlock;
import net.mcreator.morevarients.block.SmoothDarkOakPlanksBlock;
import net.mcreator.morevarients.block.SmoothCrimsonStairsBlock;
import net.mcreator.morevarients.block.SmoothCrimsonSlabBlock;
import net.mcreator.morevarients.block.SmoothCrimsonPlanksBlock;
import net.mcreator.morevarients.block.SmoothCherryStairsBlock;
import net.mcreator.morevarients.block.SmoothCherrySlabBlock;
import net.mcreator.morevarients.block.SmoothCherryPlanksBlock;
import net.mcreator.morevarients.block.SmoothBirchStairsBlock;
import net.mcreator.morevarients.block.SmoothBirchSlabBlock;
import net.mcreator.morevarients.block.SmoothBirchPlanksBlock;
import net.mcreator.morevarients.block.SmoothAcaciaStairsBlock;
import net.mcreator.morevarients.block.SmoothAcaciaSlabBlock;
import net.mcreator.morevarients.block.SmoothAcaciaPlanksBlock;
import net.mcreator.morevarients.block.RedTerracottaStairsBlock;
import net.mcreator.morevarients.block.RedTerracottaSlabBlock;
import net.mcreator.morevarients.block.RedConcreteStairsBlock;
import net.mcreator.morevarients.block.RedConcreteSlabBlock;
import net.mcreator.morevarients.block.QuartzWallsBlock;
import net.mcreator.morevarients.block.QuartzBrickWallsBlock;
import net.mcreator.morevarients.block.QuartzBrickStairsBlock;
import net.mcreator.morevarients.block.QuartzBrickSlabBlock;
import net.mcreator.morevarients.block.PurpleTerracottaStairsBlock;
import net.mcreator.morevarients.block.PurpleTerracottaSlabBlock;
import net.mcreator.morevarients.block.PurpleConcreteStairsBlock;
import net.mcreator.morevarients.block.PurpleConcreteSlabBlock;
import net.mcreator.morevarients.block.PinkTerracottaStairsBlock;
import net.mcreator.morevarients.block.PinkTerracottaSlabBlock;
import net.mcreator.morevarients.block.PinkConcreteStairsBlock;
import net.mcreator.morevarients.block.PinkConcreteSlabBlock;
import net.mcreator.morevarients.block.PillaredQuartzWallBlock;
import net.mcreator.morevarients.block.OrangeTerracottaStairsBlock;
import net.mcreator.morevarients.block.OrangeTerracottaSlabBlock;
import net.mcreator.morevarients.block.OrangeConcreteStairsBlock;
import net.mcreator.morevarients.block.OrangeConcreteSlabBlock;
import net.mcreator.morevarients.block.OakStairsBlock;
import net.mcreator.morevarients.block.OakPillarsBlock;
import net.mcreator.morevarients.block.OakMosaicSlabBlock;
import net.mcreator.morevarients.block.OakMosaicBlock;
import net.mcreator.morevarients.block.MangroveStairsBlock;
import net.mcreator.morevarients.block.MangroveMosaicSlabBlock;
import net.mcreator.morevarients.block.MangroveMosaicBlock;
import net.mcreator.morevarients.block.MagentaTerracottaStairsBlock;
import net.mcreator.morevarients.block.MagentaTerracottaSlabBlock;
import net.mcreator.morevarients.block.MagentaConcreteStairsBlock;
import net.mcreator.morevarients.block.MagentaConcreteSlabBlock;
import net.mcreator.morevarients.block.LimeTerracottaStairsBlock;
import net.mcreator.morevarients.block.LimeTerracottaSlabBlock;
import net.mcreator.morevarients.block.LimeConcreteStairsBlock;
import net.mcreator.morevarients.block.LimeConcreteSlabBlock;
import net.mcreator.morevarients.block.LightGrayTerracottaStairsBlock;
import net.mcreator.morevarients.block.LightGrayTerracottaSlabBlock;
import net.mcreator.morevarients.block.LightGrayConcreteStairsBlock;
import net.mcreator.morevarients.block.LightGrayConcreteSlabBlock;
import net.mcreator.morevarients.block.LightBlueTerracottaSlabBlock;
import net.mcreator.morevarients.block.LightBlueTerracottaBlock;
import net.mcreator.morevarients.block.LightBlueConcreteStairsBlock;
import net.mcreator.morevarients.block.LightBlueConcreteSlabBlock;
import net.mcreator.morevarients.block.JungleSatirsBlock;
import net.mcreator.morevarients.block.JungleMosaicSlabBlock;
import net.mcreator.morevarients.block.JungleMosaicBlock;
import net.mcreator.morevarients.block.GreenTerracottaStairsBlock;
import net.mcreator.morevarients.block.GreenTerracottaSlabBlock;
import net.mcreator.morevarients.block.GreenConcreteStairsBlock;
import net.mcreator.morevarients.block.GreenConcreteSlabBlock;
import net.mcreator.morevarients.block.GrayTerracottaStairsBlock;
import net.mcreator.morevarients.block.GrayTerracottaSalbBlock;
import net.mcreator.morevarients.block.GrayConcreteStairsBlock;
import net.mcreator.morevarients.block.GrayConcreteSlabBlock;
import net.mcreator.morevarients.block.GraniteBricksBlock;
import net.mcreator.morevarients.block.GraniteBrickWallBlock;
import net.mcreator.morevarients.block.GraniteBrickStairsBlock;
import net.mcreator.morevarients.block.GraniteBrickSlabBlock;
import net.mcreator.morevarients.block.DioriteBricksBlock;
import net.mcreator.morevarients.block.DioriteBrickWallBlock;
import net.mcreator.morevarients.block.DioriteBrickStairsBlock;
import net.mcreator.morevarients.block.DioriteBrickSlabBlock;
import net.mcreator.morevarients.block.DarkOakStairsBlock;
import net.mcreator.morevarients.block.DarkOakMosaicSlabBlock;
import net.mcreator.morevarients.block.DarkOakMosaicBlock;
import net.mcreator.morevarients.block.CyanTerracottaStairsBlock;
import net.mcreator.morevarients.block.CyanTerracottaSlabBlock;
import net.mcreator.morevarients.block.CyanConcreteStairsBlock;
import net.mcreator.morevarients.block.CyanConcreteSlabBlock;
import net.mcreator.morevarients.block.CrimsonMosaicStairsBlock;
import net.mcreator.morevarients.block.CrimsonMosaicSlabBlock;
import net.mcreator.morevarients.block.CrimsonMosaicBlock;
import net.mcreator.morevarients.block.CrackedPolishedGraniteBlock;
import net.mcreator.morevarients.block.CrackedPolishedDioriteBlock;
import net.mcreator.morevarients.block.CrackedPolishedDeepslateBlock;
import net.mcreator.morevarients.block.CrackedPolishedBlackstoneBlock;
import net.mcreator.morevarients.block.CrackedPolishedAndesiteBlock;
import net.mcreator.morevarients.block.ChiseledOakLogBlock;
import net.mcreator.morevarients.block.ChiseledBirchLogBlock;
import net.mcreator.morevarients.block.ChiseledAcaciaLogBlock;
import net.mcreator.morevarients.block.ChippedWarpedStemBlock;
import net.mcreator.morevarients.block.ChippedSpruceLogBlock;
import net.mcreator.morevarients.block.ChippedMangroveLogBlock;
import net.mcreator.morevarients.block.ChippedJungleLogBlock;
import net.mcreator.morevarients.block.ChippedDarkOakLogBlock;
import net.mcreator.morevarients.block.ChippedCrimsonStemBlock;
import net.mcreator.morevarients.block.ChippedCherryLogBlock;
import net.mcreator.morevarients.block.CherryMosaicStairsBlock;
import net.mcreator.morevarients.block.CherryMosaicSlabBlock;
import net.mcreator.morevarients.block.CherryMosaicBlock;
import net.mcreator.morevarients.block.BrownTerracottaStairsBlock;
import net.mcreator.morevarients.block.BrownTerracottaSlabBlock;
import net.mcreator.morevarients.block.BrownConcreteStairsBlock;
import net.mcreator.morevarients.block.BrownConcreteSlabBlock;
import net.mcreator.morevarients.block.BlueTerracottaStairsBlock;
import net.mcreator.morevarients.block.BlueTerracottaSlabBlock;
import net.mcreator.morevarients.block.BlueConcreteStairsBlock;
import net.mcreator.morevarients.block.BlueConcreteSlabBlock;
import net.mcreator.morevarients.block.BlackTerracottaStaitsBlock;
import net.mcreator.morevarients.block.BlackTerracottaSlabBlock;
import net.mcreator.morevarients.block.BlackConcreteStairsBlock;
import net.mcreator.morevarients.block.BlackConcreteSlabBlock;
import net.mcreator.morevarients.block.BirchMosaicStairsBlock;
import net.mcreator.morevarients.block.BirchMosaicSlabBlock;
import net.mcreator.morevarients.block.BirchMosaicBlock;
import net.mcreator.morevarients.block.AndesiteBricksBlock;
import net.mcreator.morevarients.block.AndesiteBrickWallBlock;
import net.mcreator.morevarients.block.AndesiteBrickStairsBlock;
import net.mcreator.morevarients.block.AndesiteBrickSlabBlock;
import net.mcreator.morevarients.block.AcaciaMosaicStairsBlock;
import net.mcreator.morevarients.block.AcaciaMosaicSlabBlock;
import net.mcreator.morevarients.block.AcaciaMosaicBlock;
import net.mcreator.morevarients.MoreVarientsMod;

public class MoreVarientsModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, MoreVarientsMod.MODID);
	public static final RegistryObject<Block> WHITE_CONCRETE_STAIRS = REGISTRY.register("white_concrete_stairs", () -> new WhiteConcreteStairsBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_STAIRS = REGISTRY.register("light_gray_concrete_stairs", () -> new LightGrayConcreteStairsBlock());
	public static final RegistryObject<Block> GRAY_CONCRETE_STAIRS = REGISTRY.register("gray_concrete_stairs", () -> new GrayConcreteStairsBlock());
	public static final RegistryObject<Block> BLACK_CONCRETE_STAIRS = REGISTRY.register("black_concrete_stairs", () -> new BlackConcreteStairsBlock());
	public static final RegistryObject<Block> BROWN_CONCRETE_STAIRS = REGISTRY.register("brown_concrete_stairs", () -> new BrownConcreteStairsBlock());
	public static final RegistryObject<Block> RED_CONCRETE_STAIRS = REGISTRY.register("red_concrete_stairs", () -> new RedConcreteStairsBlock());
	public static final RegistryObject<Block> ORANGE_CONCRETE_STAIRS = REGISTRY.register("orange_concrete_stairs", () -> new OrangeConcreteStairsBlock());
	public static final RegistryObject<Block> YELLOW_CONCRETE_STAIRS = REGISTRY.register("yellow_concrete_stairs", () -> new YellowConcreteStairsBlock());
	public static final RegistryObject<Block> LIME_CONCRETE_STAIRS = REGISTRY.register("lime_concrete_stairs", () -> new LimeConcreteStairsBlock());
	public static final RegistryObject<Block> GREEN_CONCRETE_STAIRS = REGISTRY.register("green_concrete_stairs", () -> new GreenConcreteStairsBlock());
	public static final RegistryObject<Block> CYAN_CONCRETE_STAIRS = REGISTRY.register("cyan_concrete_stairs", () -> new CyanConcreteStairsBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_STAIRS = REGISTRY.register("light_blue_concrete_stairs", () -> new LightBlueConcreteStairsBlock());
	public static final RegistryObject<Block> BLUE_CONCRETE_STAIRS = REGISTRY.register("blue_concrete_stairs", () -> new BlueConcreteStairsBlock());
	public static final RegistryObject<Block> PURPLE_CONCRETE_STAIRS = REGISTRY.register("purple_concrete_stairs", () -> new PurpleConcreteStairsBlock());
	public static final RegistryObject<Block> MAGENTA_CONCRETE_STAIRS = REGISTRY.register("magenta_concrete_stairs", () -> new MagentaConcreteStairsBlock());
	public static final RegistryObject<Block> PINK_CONCRETE_STAIRS = REGISTRY.register("pink_concrete_stairs", () -> new PinkConcreteStairsBlock());
	public static final RegistryObject<Block> WHITE_TERRACOTTA_STAIRS = REGISTRY.register("white_terracotta_stairs", () -> new WhiteTerracottaBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_TERRACOTTA_STAIRS = REGISTRY.register("light_gray_terracotta_stairs", () -> new LightGrayTerracottaStairsBlock());
	public static final RegistryObject<Block> GRAY_TERRACOTTA_STAIRS = REGISTRY.register("gray_terracotta_stairs", () -> new GrayTerracottaStairsBlock());
	public static final RegistryObject<Block> BLACK_TERRACOTTA_STAITS = REGISTRY.register("black_terracotta_staits", () -> new BlackTerracottaStaitsBlock());
	public static final RegistryObject<Block> BROWN_TERRACOTTA_STAIRS = REGISTRY.register("brown_terracotta_stairs", () -> new BrownTerracottaStairsBlock());
	public static final RegistryObject<Block> RED_TERRACOTTA_STAIRS = REGISTRY.register("red_terracotta_stairs", () -> new RedTerracottaStairsBlock());
	public static final RegistryObject<Block> ORANGE_TERRACOTTA_STAIRS = REGISTRY.register("orange_terracotta_stairs", () -> new OrangeTerracottaStairsBlock());
	public static final RegistryObject<Block> YELLOW_TERRACOTTA_STAIRS = REGISTRY.register("yellow_terracotta_stairs", () -> new YellowTerracottaStairsBlock());
	public static final RegistryObject<Block> LIME_TERRACOTTA_STAIRS = REGISTRY.register("lime_terracotta_stairs", () -> new LimeTerracottaStairsBlock());
	public static final RegistryObject<Block> GREEN_TERRACOTTA_STAIRS = REGISTRY.register("green_terracotta_stairs", () -> new GreenTerracottaStairsBlock());
	public static final RegistryObject<Block> CYAN_TERRACOTTA_STAIRS = REGISTRY.register("cyan_terracotta_stairs", () -> new CyanTerracottaStairsBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_TERRACOTTA = REGISTRY.register("light_blue_terracotta", () -> new LightBlueTerracottaBlock());
	public static final RegistryObject<Block> BLUE_TERRACOTTA_STAIRS = REGISTRY.register("blue_terracotta_stairs", () -> new BlueTerracottaStairsBlock());
	public static final RegistryObject<Block> PURPLE_TERRACOTTA_STAIRS = REGISTRY.register("purple_terracotta_stairs", () -> new PurpleTerracottaStairsBlock());
	public static final RegistryObject<Block> MAGENTA_TERRACOTTA_STAIRS = REGISTRY.register("magenta_terracotta_stairs", () -> new MagentaTerracottaStairsBlock());
	public static final RegistryObject<Block> PINK_TERRACOTTA_STAIRS = REGISTRY.register("pink_terracotta_stairs", () -> new PinkTerracottaStairsBlock());
	public static final RegistryObject<Block> TERRACOTTA_STAIRS = REGISTRY.register("terracotta_stairs", () -> new TerracottaStairsBlock());
	public static final RegistryObject<Block> THACTHED_STAIRS = REGISTRY.register("thacthed_stairs", () -> new ThacthedStairsBlock());
	public static final RegistryObject<Block> SMOOTH_STONE_STAIRS = REGISTRY.register("smooth_stone_stairs", () -> new SmoothStoneStairsBlock());
	public static final RegistryObject<Block> GRANITE_BRICK_STAIRS = REGISTRY.register("granite_brick_stairs", () -> new GraniteBrickStairsBlock());
	public static final RegistryObject<Block> ANDESITE_BRICK_STAIRS = REGISTRY.register("andesite_brick_stairs", () -> new AndesiteBrickStairsBlock());
	public static final RegistryObject<Block> DIORITE_BRICK_STAIRS = REGISTRY.register("diorite_brick_stairs", () -> new DioriteBrickStairsBlock());
	public static final RegistryObject<Block> QUARTZ_BRICK_STAIRS = REGISTRY.register("quartz_brick_stairs", () -> new QuartzBrickStairsBlock());
	public static final RegistryObject<Block> ACACIA_MOSAIC_STAIRS = REGISTRY.register("acacia_mosaic_stairs", () -> new AcaciaMosaicStairsBlock());
	public static final RegistryObject<Block> BIRCH_MOSAIC_STAIRS = REGISTRY.register("birch_mosaic_stairs", () -> new BirchMosaicStairsBlock());
	public static final RegistryObject<Block> CHERRY_MOSAIC_STAIRS = REGISTRY.register("cherry_mosaic_stairs", () -> new CherryMosaicStairsBlock());
	public static final RegistryObject<Block> CRIMSON_MOSAIC_STAIRS = REGISTRY.register("crimson_mosaic_stairs", () -> new CrimsonMosaicStairsBlock());
	public static final RegistryObject<Block> DARK_OAK_MOSAIC_STAIRS = REGISTRY.register("dark_oak_mosaic_stairs", () -> new DarkOakStairsBlock());
	public static final RegistryObject<Block> JUNGLE_MOSAIC_STAIRS = REGISTRY.register("jungle_mosaic_stairs", () -> new JungleSatirsBlock());
	public static final RegistryObject<Block> MANGROVE_MOSAIC_STAIRS = REGISTRY.register("mangrove_mosaic_stairs", () -> new MangroveStairsBlock());
	public static final RegistryObject<Block> OAK_MOSAIC_STAIRS = REGISTRY.register("oak_mosaic_stairs", () -> new OakStairsBlock());
	public static final RegistryObject<Block> SPRUCE_MOSAIC_STAIRS = REGISTRY.register("spruce_mosaic_stairs", () -> new SpruceMosaicStairsBlock());
	public static final RegistryObject<Block> WARPED_MOSAIC_STAIRS = REGISTRY.register("warped_mosaic_stairs", () -> new WarpedStairsBlock());
	public static final RegistryObject<Block> SMOOTH_ACACIA_STAIRS = REGISTRY.register("smooth_acacia_stairs", () -> new SmoothAcaciaStairsBlock());
	public static final RegistryObject<Block> SMOOTH_BIRCH_STAIRS = REGISTRY.register("smooth_birch_stairs", () -> new SmoothBirchStairsBlock());
	public static final RegistryObject<Block> SMOOTH_CHERRY_STAIRS = REGISTRY.register("smooth_cherry_stairs", () -> new SmoothCherryStairsBlock());
	public static final RegistryObject<Block> SMOOTH_CRIMSON_STAIRS = REGISTRY.register("smooth_crimson_stairs", () -> new SmoothCrimsonStairsBlock());
	public static final RegistryObject<Block> SMOOTH_DARK_OAK_STAIRS = REGISTRY.register("smooth_dark_oak_stairs", () -> new SmoothDarkOakStairsBlock());
	public static final RegistryObject<Block> SMOOTH_JUNGLE_STAIRS = REGISTRY.register("smooth_jungle_stairs", () -> new SmoothJungleStairsBlock());
	public static final RegistryObject<Block> SMOOTH_MANGROVE_STAIRS = REGISTRY.register("smooth_mangrove_stairs", () -> new SmoothMangroveStairsBlock());
	public static final RegistryObject<Block> SMOOTH_OAK_STAIRS = REGISTRY.register("smooth_oak_stairs", () -> new SmoothOakStairsBlock());
	public static final RegistryObject<Block> SMOOTH_SPRUCE_SAIRS = REGISTRY.register("smooth_spruce_sairs", () -> new SmoothSpruceSairsBlock());
	public static final RegistryObject<Block> SMOOTH_WARPED_STAIRS = REGISTRY.register("smooth_warped_stairs", () -> new SmoothWarpedStairsBlock());
	public static final RegistryObject<Block> WHITE_CONCRETE_SLAB = REGISTRY.register("white_concrete_slab", () -> new WhiteConcreteSlabBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_CONCRETE_SLAB = REGISTRY.register("light_gray_concrete_slab", () -> new LightGrayConcreteSlabBlock());
	public static final RegistryObject<Block> GRAY_CONCRETE_SLAB = REGISTRY.register("gray_concrete_slab", () -> new GrayConcreteSlabBlock());
	public static final RegistryObject<Block> BLACK_CONCRETE_SLAB = REGISTRY.register("black_concrete_slab", () -> new BlackConcreteSlabBlock());
	public static final RegistryObject<Block> BROWN_CONCRETE_SLAB = REGISTRY.register("brown_concrete_slab", () -> new BrownConcreteSlabBlock());
	public static final RegistryObject<Block> RED_CONCRETE_SLAB = REGISTRY.register("red_concrete_slab", () -> new RedConcreteSlabBlock());
	public static final RegistryObject<Block> ORANGE_CONCRETE_SLAB = REGISTRY.register("orange_concrete_slab", () -> new OrangeConcreteSlabBlock());
	public static final RegistryObject<Block> YELLOW_CONCRETE_SLAB = REGISTRY.register("yellow_concrete_slab", () -> new YellowConcreteSlabBlock());
	public static final RegistryObject<Block> LIME_CONCRETE_SLAB = REGISTRY.register("lime_concrete_slab", () -> new LimeConcreteSlabBlock());
	public static final RegistryObject<Block> GREEN_CONCRETE_SLAB = REGISTRY.register("green_concrete_slab", () -> new GreenConcreteSlabBlock());
	public static final RegistryObject<Block> CYAN_CONCRETE_SLAB = REGISTRY.register("cyan_concrete_slab", () -> new CyanConcreteSlabBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_CONCRETE_SLAB = REGISTRY.register("light_blue_concrete_slab", () -> new LightBlueConcreteSlabBlock());
	public static final RegistryObject<Block> BLUE_CONCRETE_SLAB = REGISTRY.register("blue_concrete_slab", () -> new BlueConcreteSlabBlock());
	public static final RegistryObject<Block> PURPLE_CONCRETE_SLAB = REGISTRY.register("purple_concrete_slab", () -> new PurpleConcreteSlabBlock());
	public static final RegistryObject<Block> MAGENTA_CONCRETE_SLAB = REGISTRY.register("magenta_concrete_slab", () -> new MagentaConcreteSlabBlock());
	public static final RegistryObject<Block> PINK_CONCRETE_SLAB = REGISTRY.register("pink_concrete_slab", () -> new PinkConcreteSlabBlock());
	public static final RegistryObject<Block> TERRACOTTA_SLAB = REGISTRY.register("terracotta_slab", () -> new TerracottaSlabBlock());
	public static final RegistryObject<Block> WHITE_TERRACOTTA_SLAB = REGISTRY.register("white_terracotta_slab", () -> new WhiteTerracottaSlabBlock());
	public static final RegistryObject<Block> LIGHT_GRAY_TERRACOTTA_SLAB = REGISTRY.register("light_gray_terracotta_slab", () -> new LightGrayTerracottaSlabBlock());
	public static final RegistryObject<Block> GRAY_TERRACOTTA_SALB = REGISTRY.register("gray_terracotta_salb", () -> new GrayTerracottaSalbBlock());
	public static final RegistryObject<Block> BROWN_TERRACOTTA_SLAB = REGISTRY.register("brown_terracotta_slab", () -> new BrownTerracottaSlabBlock());
	public static final RegistryObject<Block> BLACK_TERRACOTTA_SLAB = REGISTRY.register("black_terracotta_slab", () -> new BlackTerracottaSlabBlock());
	public static final RegistryObject<Block> THATCHED_SLAB = REGISTRY.register("thatched_slab", () -> new ThatchedSlabBlock());
	public static final RegistryObject<Block> GRANITE_BRICK_SLAB = REGISTRY.register("granite_brick_slab", () -> new GraniteBrickSlabBlock());
	public static final RegistryObject<Block> DIORITE_BRICK_SLAB = REGISTRY.register("diorite_brick_slab", () -> new DioriteBrickSlabBlock());
	public static final RegistryObject<Block> ANDESITE_BRICK_SLAB = REGISTRY.register("andesite_brick_slab", () -> new AndesiteBrickSlabBlock());
	public static final RegistryObject<Block> QUARTZ_BRICK_SLAB = REGISTRY.register("quartz_brick_slab", () -> new QuartzBrickSlabBlock());
	public static final RegistryObject<Block> ACACIA_MOSAIC_SLAB = REGISTRY.register("acacia_mosaic_slab", () -> new AcaciaMosaicSlabBlock());
	public static final RegistryObject<Block> BIRCH_MOSAIC_SLAB = REGISTRY.register("birch_mosaic_slab", () -> new BirchMosaicSlabBlock());
	public static final RegistryObject<Block> CHERRY_MOSAIC_SLAB = REGISTRY.register("cherry_mosaic_slab", () -> new CherryMosaicSlabBlock());
	public static final RegistryObject<Block> CRIMSON_MOSAIC_SLAB = REGISTRY.register("crimson_mosaic_slab", () -> new CrimsonMosaicSlabBlock());
	public static final RegistryObject<Block> DARK_OAK_MOSAIC_SLAB = REGISTRY.register("dark_oak_mosaic_slab", () -> new DarkOakMosaicSlabBlock());
	public static final RegistryObject<Block> JUNGLE_MOSAIC_SLAB = REGISTRY.register("jungle_mosaic_slab", () -> new JungleMosaicSlabBlock());
	public static final RegistryObject<Block> MANGROVE_MOSAIC_SLAB = REGISTRY.register("mangrove_mosaic_slab", () -> new MangroveMosaicSlabBlock());
	public static final RegistryObject<Block> OAK_MOSAIC_SLAB = REGISTRY.register("oak_mosaic_slab", () -> new OakMosaicSlabBlock());
	public static final RegistryObject<Block> SPRUCE_MOSAIC_SLAB = REGISTRY.register("spruce_mosaic_slab", () -> new SpruceMosaicSlabBlock());
	public static final RegistryObject<Block> WARPED_MOSAIC_SLAB = REGISTRY.register("warped_mosaic_slab", () -> new WarpedMosaicSlabBlock());
	public static final RegistryObject<Block> SMOOTH_ACACIA_SLAB = REGISTRY.register("smooth_acacia_slab", () -> new SmoothAcaciaSlabBlock());
	public static final RegistryObject<Block> SMOOTH_BIRCH_SLAB = REGISTRY.register("smooth_birch_slab", () -> new SmoothBirchSlabBlock());
	public static final RegistryObject<Block> SMOOTH_CHERRY_SLAB = REGISTRY.register("smooth_cherry_slab", () -> new SmoothCherrySlabBlock());
	public static final RegistryObject<Block> SMOOTH_CRIMSON_SLAB = REGISTRY.register("smooth_crimson_slab", () -> new SmoothCrimsonSlabBlock());
	public static final RegistryObject<Block> SMOOTH_DARK_OAK_SLAB = REGISTRY.register("smooth_dark_oak_slab", () -> new SmoothDarkOakSlabBlock());
	public static final RegistryObject<Block> SMOOTH_JUNGLE_SLAB = REGISTRY.register("smooth_jungle_slab", () -> new SmoothJungleSlabBlock());
	public static final RegistryObject<Block> SMOOTH_MANGROVE_SLAB = REGISTRY.register("smooth_mangrove_slab", () -> new SmoothMangroveSlabBlock());
	public static final RegistryObject<Block> SMOOTH_OAK_SLAB = REGISTRY.register("smooth_oak_slab", () -> new SmoothOakSlabBlock());
	public static final RegistryObject<Block> SMOOTH_SPRUCE_SLAB = REGISTRY.register("smooth_spruce_slab", () -> new SmoothSpruceSlabBlock());
	public static final RegistryObject<Block> SMOOTH_WARPED_SLAB = REGISTRY.register("smooth_warped_slab", () -> new SmoothWarpedSlabBlock());
	public static final RegistryObject<Block> CRACKED_POLISHED_GRANITE = REGISTRY.register("cracked_polished_granite", () -> new CrackedPolishedGraniteBlock());
	public static final RegistryObject<Block> CRACKED_POLISHED_ANDESITE = REGISTRY.register("cracked_polished_andesite", () -> new CrackedPolishedAndesiteBlock());
	public static final RegistryObject<Block> CRACKED_POLISHED_DIORITE = REGISTRY.register("cracked_polished_diorite", () -> new CrackedPolishedDioriteBlock());
	public static final RegistryObject<Block> CRACKED_POLISHED_DEEPSLATE = REGISTRY.register("cracked_polished_deepslate", () -> new CrackedPolishedDeepslateBlock());
	public static final RegistryObject<Block> CRACKED_POLISHED_BLACKSTONE = REGISTRY.register("cracked_polished_blackstone", () -> new CrackedPolishedBlackstoneBlock());
	public static final RegistryObject<Block> GRANITE_BRICKS = REGISTRY.register("granite_bricks", () -> new GraniteBricksBlock());
	public static final RegistryObject<Block> DIORITE_BRICKS = REGISTRY.register("diorite_bricks", () -> new DioriteBricksBlock());
	public static final RegistryObject<Block> ANDESITE_BRICKS = REGISTRY.register("andesite_bricks", () -> new AndesiteBricksBlock());
	public static final RegistryObject<Block> CHIPPED_ACACIA_LOG = REGISTRY.register("chipped_acacia_log", () -> new ChiseledAcaciaLogBlock());
	public static final RegistryObject<Block> CHIPPED_BIRCH_LOG = REGISTRY.register("chipped_birch_log", () -> new ChiseledBirchLogBlock());
	public static final RegistryObject<Block> CHIPPED_CHERRY_LOG = REGISTRY.register("chipped_cherry_log", () -> new ChippedCherryLogBlock());
	public static final RegistryObject<Block> CHIPPED_CRIMSON_STEM = REGISTRY.register("chipped_crimson_stem", () -> new ChippedCrimsonStemBlock());
	public static final RegistryObject<Block> CHIPPED_DARK_OAK_LOG = REGISTRY.register("chipped_dark_oak_log", () -> new ChippedDarkOakLogBlock());
	public static final RegistryObject<Block> CHIPPED_JUNGLE_LOG = REGISTRY.register("chipped_jungle_log", () -> new ChippedJungleLogBlock());
	public static final RegistryObject<Block> CHIPPED_MANGROVE_LOG = REGISTRY.register("chipped_mangrove_log", () -> new ChippedMangroveLogBlock());
	public static final RegistryObject<Block> CHIPPED_OAK_LOG = REGISTRY.register("chipped_oak_log", () -> new ChiseledOakLogBlock());
	public static final RegistryObject<Block> CHIPPED_SPRUCE_LOG = REGISTRY.register("chipped_spruce_log", () -> new ChippedSpruceLogBlock());
	public static final RegistryObject<Block> CHIPPED_WARPED_STEM = REGISTRY.register("chipped_warped_stem", () -> new ChippedWarpedStemBlock());
	public static final RegistryObject<Block> ACACIA_MOSAIC = REGISTRY.register("acacia_mosaic", () -> new AcaciaMosaicBlock());
	public static final RegistryObject<Block> BIRCH_MOSAIC = REGISTRY.register("birch_mosaic", () -> new BirchMosaicBlock());
	public static final RegistryObject<Block> CHERRY_MOSAIC = REGISTRY.register("cherry_mosaic", () -> new CherryMosaicBlock());
	public static final RegistryObject<Block> CRIMSON_MOSAIC = REGISTRY.register("crimson_mosaic", () -> new CrimsonMosaicBlock());
	public static final RegistryObject<Block> DARK_OAK_MOSAIC = REGISTRY.register("dark_oak_mosaic", () -> new DarkOakMosaicBlock());
	public static final RegistryObject<Block> JUNGLE_MOSAIC = REGISTRY.register("jungle_mosaic", () -> new JungleMosaicBlock());
	public static final RegistryObject<Block> MANGROVE_MOSAIC = REGISTRY.register("mangrove_mosaic", () -> new MangroveMosaicBlock());
	public static final RegistryObject<Block> OAK_MOSAIC = REGISTRY.register("oak_mosaic", () -> new OakMosaicBlock());
	public static final RegistryObject<Block> SPRUCE_MOSAIC = REGISTRY.register("spruce_mosaic", () -> new SpruceMosaicBlock());
	public static final RegistryObject<Block> WARPED_MOSAIC = REGISTRY.register("warped_mosaic", () -> new WarpedMosaicBlock());
	public static final RegistryObject<Block> SMOOTH_ACACIA_PLANKS = REGISTRY.register("smooth_acacia_planks", () -> new SmoothAcaciaPlanksBlock());
	public static final RegistryObject<Block> SMOOTH_BIRCH_PLANKS = REGISTRY.register("smooth_birch_planks", () -> new SmoothBirchPlanksBlock());
	public static final RegistryObject<Block> SMOOTH_CHERRY_PLANKS = REGISTRY.register("smooth_cherry_planks", () -> new SmoothCherryPlanksBlock());
	public static final RegistryObject<Block> SMOOTH_CRIMSON_PLANKS = REGISTRY.register("smooth_crimson_planks", () -> new SmoothCrimsonPlanksBlock());
	public static final RegistryObject<Block> SMOOTH_DARK_OAK_PLANKS = REGISTRY.register("smooth_dark_oak_planks", () -> new SmoothDarkOakPlanksBlock());
	public static final RegistryObject<Block> SMOOTH_JUNGLE_PLANKS = REGISTRY.register("smooth_jungle_planks", () -> new SmoothJunglePlanksBlock());
	public static final RegistryObject<Block> SMOOTH_MANGROVE_PLANKS = REGISTRY.register("smooth_mangrove_planks", () -> new SmoothMangrovePlanksBlock());
	public static final RegistryObject<Block> SMOOTH_OAK_PLANKS = REGISTRY.register("smooth_oak_planks", () -> new SmoothOakPlanksBlock());
	public static final RegistryObject<Block> SMOOTH_SPRUCE_PLANKS = REGISTRY.register("smooth_spruce_planks", () -> new SmoothSprucePlanksBlock());
	public static final RegistryObject<Block> SMOOTH_WARPED_PLANKS = REGISTRY.register("smooth_warped_planks", () -> new SmoothWarpedPlanksBlock());
	public static final RegistryObject<Block> OAK_PILLARS = REGISTRY.register("oak_pillars", () -> new OakPillarsBlock());
	public static final RegistryObject<Block> GRANITE_BRICK_WALL = REGISTRY.register("granite_brick_wall", () -> new GraniteBrickWallBlock());
	public static final RegistryObject<Block> DIORITE_BRICK_WALL = REGISTRY.register("diorite_brick_wall", () -> new DioriteBrickWallBlock());
	public static final RegistryObject<Block> ANDESITE_BRICK_WALL = REGISTRY.register("andesite_brick_wall", () -> new AndesiteBrickWallBlock());
	public static final RegistryObject<Block> QUARTZ_WALLS = REGISTRY.register("quartz_walls", () -> new QuartzWallsBlock());
	public static final RegistryObject<Block> QUARTZ_BRICK_WALLS = REGISTRY.register("quartz_brick_walls", () -> new QuartzBrickWallsBlock());
	public static final RegistryObject<Block> SMOOTH_QUARTZ_WALLS = REGISTRY.register("smooth_quartz_walls", () -> new SmoothQuartzWallsBlock());
	public static final RegistryObject<Block> PILLARED_QUARTZ_WALL = REGISTRY.register("pillared_quartz_wall", () -> new PillaredQuartzWallBlock());
	public static final RegistryObject<Block> RED_TERRACOTTA_SLAB = REGISTRY.register("red_terracotta_slab", () -> new RedTerracottaSlabBlock());
	public static final RegistryObject<Block> ORANGE_TERRACOTTA_SLAB = REGISTRY.register("orange_terracotta_slab", () -> new OrangeTerracottaSlabBlock());
	public static final RegistryObject<Block> YELLOW_TERRACOTTA_SLAB = REGISTRY.register("yellow_terracotta_slab", () -> new YellowTerracottaSlabBlock());
	public static final RegistryObject<Block> LIME_TERRACOTTA_SLAB = REGISTRY.register("lime_terracotta_slab", () -> new LimeTerracottaSlabBlock());
	public static final RegistryObject<Block> GREEN_TERRACOTTA_SLAB = REGISTRY.register("green_terracotta_slab", () -> new GreenTerracottaSlabBlock());
	public static final RegistryObject<Block> CYAN_TERRACOTTA_SLAB = REGISTRY.register("cyan_terracotta_slab", () -> new CyanTerracottaSlabBlock());
	public static final RegistryObject<Block> LIGHT_BLUE_TERRACOTTA_SLAB = REGISTRY.register("light_blue_terracotta_slab", () -> new LightBlueTerracottaSlabBlock());
	public static final RegistryObject<Block> BLUE_TERRACOTTA_SLAB = REGISTRY.register("blue_terracotta_slab", () -> new BlueTerracottaSlabBlock());
	public static final RegistryObject<Block> PURPLE_TERRACOTTA_SLAB = REGISTRY.register("purple_terracotta_slab", () -> new PurpleTerracottaSlabBlock());
	public static final RegistryObject<Block> MAGENTA_TERRACOTTA_SLAB = REGISTRY.register("magenta_terracotta_slab", () -> new MagentaTerracottaSlabBlock());
	public static final RegistryObject<Block> PINK_TERRACOTTA_SLAB = REGISTRY.register("pink_terracotta_slab", () -> new PinkTerracottaSlabBlock());
}
